### ISSUE TITLE
Chat Bubbles not filling, stuck in outline

### ISSUE THREAD

**Issue by ewfatchicks** [MTACS/DopeConvos#130]
**Describe the bug**
Once I started configuring with the tweak, I noticed my chat bubbles were stuck in this rectangular form with a weird block of color in the middle. This persisted even after I turned off the tweak. The only way to correct it is to either select the outline option or to completely un-jailbreak my phone. I'd rather have the chat bubbles filled in with color.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
![IMG_8490](https://user-images.githubusercontent.com/68450711/87840942-cc1f2000-c867-11ea-9be6-9803cb35b9c9.PNG)
 I selected the preset "DopeConvosSunset" so the presets can be easily found/known. The pictures are also see though, but I just thought that was a sacrifice.
Device type: [iPhone XS Max]
iOS Version: [ex. 13.5]
Package Manager: [Zebra]
Tweak Version: [3.3]

**Comment by rileyjw90** [comment]
I’m having this exact problem. I’ve tried resetting preferences, uninstalling and reinstalling, importing profiles, nothing is working. And now my messages are stuck, even when I completely uninstall, they still have this weird outline with a smaller color box inside. When I uncheck outline and just have gradient, the colors aren’t what I chose but the default iMessage blue/green. The only thing I’ve been able to do is to make the colors transparent, but then I’m left with floating messages all over the place with no defined bubbles at all. 
![78270798-BE4E-4F00-8F2F-BBAC0853CC4B](https://user-images.githubusercontent.com/64595997/90540318-10dff480-e14f-11ea-9909-11d97552fc6b.jpeg)

**Comment by rileyjw90** [comment]
Alright. After trying literally everything I could think of with no success, I finally figured out what the problem is (at least for me!). I’ve got Reva UI, which comes with a “tailless” message bubble option. If you also have the tailless bubble option selected in DopeConvos, it will do this weird outline thing. You have to do one or the other, you can’t have both enabled at the same time. I assume any tweak that affects the bubble shapes will have a similar conflict. Hope this can help someone! 

![B14DE931-7648-4815-A562-5DE90633941A](https://user-images.githubusercontent.com/64595997/90553325-31657a00-e162-11ea-9aca-8cc215cabee6.jpeg)

**Comment by nahtedetihw** [comment]
Enable UI Theming in DopeConvos>Main Settings>Bubbles>Gradient Bubbles
